
#!/usr/bin/env bash
# setup-gcon2-serial.sh
#
# Creates exactly TWO symlinks via udev:
#   /dev/ttyGCON2S_0  -> the active primary UART (whatever /dev/serial0 resolves to)
#   /dev/ttyGCON2S_1  -> UART5 (ttyAMA5 or ttyS5, depending on overlay/SoC)
#
# And TWO picocom aliases (loaded system-wide):
#   ttyGCON2S_0
#   ttyGCON2S_1
#
# Default baud: 115200 (override: export BAUD=9600 before running)

set -euo pipefail

PREFIX0="ttyGCON2S_0"
PREFIX1="ttyGCON2S_1"
BAUD="${BAUD:-115200}"
UDEV_RULE_FILE="/etc/udev/rules.d/99-gcon2-serial.rules"
PROFILE_SNIPPET="/etc/profile.d/gcon2-serial.sh"

# ---------- Utility ----------
banner() {
  local msg="$1"
  printf "\n\033[1;36m[%s]\033[0m %s\n" "GCON2-Serial" "$msg"
}

warn() {
  local msg="$1"
  printf "\033[1;33m[WARN]\033[0m %s\n" "$msg"
}

error() {
  local msg="$1"
  printf "\033[1;31m[ERROR]\033[0m %s\n" "$msg"
}

# ---------- Model detection (prints banner for Raspberry Pi 5) ----------
detect_model() {
  MODEL_STR="Unknown"
  if [[ -r /proc/device-tree/model ]]; then
    # /proc/device-tree/model is NUL-terminated; strip trailing NULs
    MODEL_STR="$(tr -d '\000' < /proc/device-tree/model 2>/dev/null || echo "Unknown")"
  elif command -v cat >/dev/null 2>&1 && [[ -r /sys/firmware/devicetree/base/model ]]; then
    MODEL_STR="$(tr -d '\000' < /sys/firmware/devicetree/base/model 2>/dev/null || echo "Unknown")"
  fi

  if echo "$MODEL_STR" | grep -qi "Raspberry Pi 5"; then
    banner "Raspberry Pi 5 detected: primary UART is typically a PL011 (ttyAMA*)."
  else
    banner "Model detected: ${MODEL_STR}"
  fi
}

# ---------- Pre-flight ----------
require_root() {
  if [[ $EUID -ne 0 ]]; then
    error "Please run as root (sudo)."
    exit 1
  fi
}

ensure_tools_and_groups() {
  # Optional: install picocom if missing (comment out in managed build pipelines)
  if ! command -v picocom >/dev/null 2>&1; then
    banner "picocom not found; installing via apt..."
    apt-get update -y && apt-get install -y picocom
  fi
  # Ensure dialout group permissions
  getent group dialout >/dev/null 2>&1 || groupadd dialout
  local u="${SUDO_USER:-$USER}"
  if ! id -nG "$u" | tr ' ' '\n' | grep -qx dialout; then
    banner "Adding $u to 'dialout' group (relog required)."
    usermod -aG dialout "$u" || true
  fi
}

# ---------- Primary UART resolution ----------
# Decide what the primary UART kernel device is (we will create ONLY ONE rule for it)
resolve_primary_kernel() {
  PRIMARY_KERNEL=""
  if [[ -e /dev/serial0 ]]; then
    local target
    target="$(readlink -f /dev/serial0 || true)"
    # Expect /dev/ttyAMA0, /dev/ttyAMA10, /dev/ttyS0, etc.
    if [[ "$target" =~ /dev/(ttyAMA[0-9]+|ttyS[0-9]+)$ ]]; then
      PRIMARY_KERNEL="${BASH_REMATCH[1]}"
    fi
  fi

  # Fallbacks if /dev/serial0 missing (unusual on Raspberry Pi OS)
  if [[ -z "$PRIMARY_KERNEL" ]]; then
    if [[ -e /dev/ttyAMA0 ]]; then PRIMARY_KERNEL="ttyAMA0"; fi
    if [[ -z "$PRIMARY_KERNEL" && -e /dev/ttyS0 ]]; then PRIMARY_KERNEL="ttyS0"; fi
  fi

  if [[ -z "$PRIMARY_KERNEL" ]]; then
    warn "Could not determine primary UART. No primary alias will be created."
  else
    banner "Primary UART resolved to: /dev/${PRIMARY_KERNEL}"
  fi
}

# ---------- udev rules ----------
write_udev_rules() {
  banner "Writing udev rules -> $UDEV_RULE_FILE"
  {
    echo '# Auto-generated by setup-gcon2-serial.sh'
    echo '# Creates exactly one primary alias and one UART5 alias.'
    echo
    if [[ -n "$PRIMARY_KERNEL" ]]; then
      # Create only ONE rule for the detected primary kernel device
      echo "SUBSYSTEM==\"tty\", KERNEL==\"${PRIMARY_KERNEL}\", SYMLINK+=\"${PREFIX0}\""
    fi
    echo
    # UART5 can surface as PL011 or miniUART
    echo "SUBSYSTEM==\"tty\", KERNEL==\"ttyAMA5\", SYMLINK+=\"${PREFIX1}\""
    echo "SUBSYSTEM==\"tty\", KERNEL==\"ttyS5\",   SYMLINK+=\"${PREFIX1}\""
    echo
    echo '# Notes:'
    echo '# - On Pi 5, /dev/serial0 typically points to a PL011 (ttyAMA*).'
    echo '# - On earlier models, it may point to ttyAMA0 or ttyS0 depending on overlays.'
  } > "$UDEV_RULE_FILE"

  udevadm control --reload
  udevadm trigger --subsystem-match=tty || true
}

# ---------- aliases ----------
write_profile_aliases() {
  banner "Creating shell aliases -> $PROFILE_SNIPPET"
  cat > "$PROFILE_SNIPPET" <<EOF
# GCON2 serial aliases (auto-generated)
# Default baud: $BAUD
alias ${PREFIX0}='picocom -b $BAUD /dev/${PREFIX0}'
alias ${PREFIX1}='picocom -b $BAUD /dev/${PREFIX1}'

gcon2_serial_status() {
  for link in /dev/${PREFIX0} /dev/${PREFIX1}; do
    if [[ -e "\$link" ]]; then
      echo "\$link -> \$(readlink -f "\$link")"
    else
      echo "\$link (missing)"
    fi
  done
}
EOF
}

# ---------- status ----------
show_status() {
  banner "Symlink status"
  for link in "/dev/${PREFIX0}" "/dev/${PREFIX1}"; do
    if [[ -e "$link" ]]; then
      echo "  Found: $link -> $(readlink -f "$link")"
    else
      echo "  Missing: $link"
    fi
  done
}

# ---------- main ----------
main() {
  require_root
  detect_model
  ensure_tools_and_groups
  resolve_primary_kernel
  write_udev_rules
  write_profile_aliases
  show_status

  echo
  echo "Next steps:"
  echo "  • If you just enabled overlays, reboot first."
  echo "  • Load aliases now:  source /etc/profile.d/gcon2-serial.sh"
  echo "  • Connect: ${PREFIX0}   (primary UART)   or   ${PREFIX1} (UART5)"
  echo "  • Check:   gcon2_serial_status"
}
main
``
